#!/usr/bin/bash
#version 1.1.0
###############################
##? BASH ? SCRIPT ? TOOLS ???##
###############################
#colors
clear
blue='\e[1;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#install
function install(){
	apt-get install ruby
	gem install lolcat
	apt-get install php
	apt-get install curl
}
#webdav
function webdav(){
	echo -e $red "Masukan Target Anda "
	read "root@target:~#" target
	sleep 1
	echo -e $green "Masukan Patch File Anda "
        read "root@file:~#" file
        sleep 1
        echo -e "Menunggu Persiapan..."
        curl -T /data/data/com.termux/files/home$file $target
}
#decoration
function decoration(){
	echo -e $red " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $red "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $red "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $red "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear 
	echo -e $blue " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $blue "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $blue "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $blue "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear
	echo -e $cyan " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $cyan "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $cyan "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $cyan "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear
	echo -e $red " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $red "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $red "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $red "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear
	clear 
	echo -e $blue " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $blue "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $blue "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $blue "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear
	echo -e $cyan " ____  __ _  _  _  _  _   __   ____  ____ "
	echo -e $cyan "/ ___)(  / )( \/ )/ )( \ / _\ (  _ \(  __)"
	echo -e $cyan "\___ \ )  (  )  / \ /\ //    \ )   / ) _) "
	echo -e $cyan "(____/(__\_)(__/  (_/\_)\_/\_/(__\_)(____)"
	sleep 0.25
	clear
}
#nmap
function nmap(){
	apt-get intall nmap
	sleep 0.25
	clear 
	echo -e $green "Silahkan gunakan nmap DENGAN mengetikan nmap -ip "
}
#bash
function bash(){
	sleep 0.25
       git clone https://github.com/tampansky/SpamBom
       sleep 0.25
       clear 
       cd SpamBom
       sleep 0.25
       clear
       chmod +x *
       clear
       ./setup.sh 
       sleep 0.25
       clear
       ./spam.sh 
}
#tampansky
function tampansky(){
	sleep 0.25
	git clone https://github.com/tampansky/installer
        sleep 0.25
        cd installer
        sleep 0.25
        clear
        chmod +x *
        sleep 0.25
        clear
        ./install
}
#recomended
function recomended(){
	 echo -e "Please Download/install..." | lolcat
}
#TU4NB4DUT
function badut(){
	sleep 0.25
	git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv4
        sleep 0.25
        clear
        cd TOOLSINSTALLERv4
        sleep 0.25
        clear 
        ./TUANB4DUT..sh
}
#FBH
function FBH(){
	sleep 0.25
	git clone https://github.com/muhammadfathul/FBH
        sleep 0.25
        clear
        cd FBH
        chmod +x *
        clear
        ./setup
        sleep 0.25
        ./FBH
}
#php
function php(){
	sleep 1
	git clone https://github.com/tampansky/SPAM.php
        sleep 0.25
        cd SPAM.php
        clear
        sleep 0.25 
        echo -e $blue "Silahkan Jalankan Sesuai Dengan Nama File TSB." 
        ls 
}
#intro
function intro (){
      sleep 0.25
      echo -e "<><><><><><><><><><><><><><><><><><><><><>" | lolcat
      sleep 0.25
      echo -e "<~______________________________________~>" | lolcat
      sleep 0.25
      echo -e "<~AUTHOR : HADI PRASETIA                ~>" | lolcat
      sleep 0.25
      echo -e "<~TEAM : Red Eye Cyber Team             ~>" | lolcat
      sleep 0.25
      echo -e "<~CONTACT : tampanskyyt@gmail.com       ~>" | lolcat
      sleep 0.25
      echo -e "<~WhatsApp : 0878-8798-6528             ~>" | lolcat
      sleep 0.25
      echo -e "<~Terima Kasih Telah Mendukung Saya     ~>" | lolcat
      sleep 0.25
      echo -e "<~Suport By Assyfamawarni and my moms   ~>" | lolcat
      sleep 0.25
      echo -e "<~______________________________________~>" | lolcat
      sleep 0.25
      echo -e "<><><><><><><><><><><><><><><><><><><><><>" | lolcat
      sleep 0.25    
}
#list menu
function menu(){
    echo -e "-______________________________________-" | lolcat 
    sleep 0.25
    echo -e $red "-1. TOOlS muhammadfathul               -" 
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $blue "-2. TOOLS Tampansky                    -"
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $green "-3. TOOLS Nmap                        -" 
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $cyan "-4. TOOLS TUANB4DUT                    -"
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $red "-5. TOOLS spam (bash)                  -"
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $blue "-6. TOOLS Spam (PHP)                   -"
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
    echo -e $red "-7. EXIT.                              -"
    sleep 0.25
    echo -e "-______________________________________-" | lolcat
    sleep 0.25
}
install 
sleep 1
decoration
clear
sleep 1
intro
sleep 0.25
menu 
read -e "root@localhost:~#" war
case $war in 
	("1")
	FBH
        ;;
        ("2")
        tampansky
         ;;
        ("3")
        nmap
        ;;
        ("4")
        badut
        ;;
        ("5")
        bash
        ;;
        ("6")
        php
        ;;
        ("7")
        intro
esac
